<?php
/**
 * Ebay edition package for Magento Localized
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalizedEbay
 * @copyright  Copyright (c) 2013 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var $this Mage_Adminhtml_Block_Template
 */
?>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('PayPal') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_paypal">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>

            <tr>
                <td class="label"><label for="field_paypal_active"><?php echo $this->__('Activate PayPal Express payment') ?></label></td>
                <td class="value">
                    <select name="paypal_active" id="field_paypal_active">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/express_checkout_required/enable_express_checkout')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/express_checkout_required/enable_express_checkout')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_paypal_sandbox"><?php echo $this->__('Test mode (sandbox) for PayPal payment') ?></label></td>
                <td class="value">
                    <select name="paypal_sandbox" id="field_paypal_sandbox">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/express_checkout_required_express_checkout/sandbox_flag')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/express_checkout_required_express_checkout/sandbox_flag')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_paypal_email"><?php echo $this->__('Email Associated with PayPal Merchant Account') ?></label></td>
                <td class="value">
                    <input type="text" name="paypal_email" id="field_paypal_email" class="input-text" value="<?php echo Mage::getStoreConfig('payment/express_checkout_required_express_checkout/business_account') ?>" />
                </td>
                <td class="comment"></td>
            </tr>

            <tr>
                <td class="label"><label for="field_paypal_api_username"><?php echo Mage::helper('paypal')->__('API Username') ?></label></td>
                <td class="value">
                    <input type="text" name="paypal_api_username" id="field_paypal_api_username" class="input-text" value="<?php echo Mage::getStoreConfig('payment/express_checkout_required_express_checkout/api_username') ?>" />
                </td>
                <td class="comment" rowspan="3">
                    <div class="pp-buttons-container">
                        <button id="payment_express_checkout_required_express_checkout_api_wizard" type="button" class="scalable" onclick="javascript:window.open('https://www.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=470'); return false;">
                            <span><span><span><?php echo Mage::helper('paypal')->__('Get Credentials from PayPal') ?></span></span></span>
                        </button>
                        <button id="sandbox_payment_express_checkout_required_express_checkout_api_wizard" type="button" class="scalable" onclick="javascript:window.open('https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=470'); return false;">
                            <span><span><span><?php echo Mage::helper('paypal')->__('Sandbox Credentials') ?></span></span></span>
                        </button>
                    </div>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_paypal_api_password"><?php echo Mage::helper('paypal')->__('API Password') ?></label></td>
                <td class="value">
                    <input type="text" name="paypal_api_password" id="field_paypal_api_password" class="input-text" value="<?php echo Mage::getStoreConfig('payment/express_checkout_required_express_checkout/api_password') ?>" />
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_paypal_api_signature"><?php echo Mage::helper('paypal')->__('API Signature') ?></label></td>
                <td class="value">
                    <input type="text" name="paypal_api_signature" id="field_paypal_api_signature" class="input-text" value="<?php echo Mage::getStoreConfig('payment/express_checkout_required_express_checkout/api_signature') ?>" />
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</div>


<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('BillSAFE') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_billsafe">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>

            <?php if (!Mage::getStoreConfig('magento_localized/installed_modules/billsafe/billsafe')): ?>
            <tr>
                <td class="label"><label for="field_billsafe_install"><?php echo $this->__('Install BillSAFE module') ?></label></td>
                <td class="value">
                    <select name="billsafe_install" id="field_billsafe_install">
                        <option value="0"><?php echo $this->__('No') ?></option>
                        <option value="1" selected="selected"><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
                <td class="comment" rowspan="3">
                    <img src="<?php echo $this->getSkinUrl('magento_localized/logo_billsafe.png') ?>" alt="BillSAFE" />
                </td>
            </tr>
            <?php endif ?>

            <tr>
                <td class="label"><label for="field_billsafe_active"><?php echo $this->__('Activate BillSAFE payment') ?></label></td>
                <td class="value">
                    <select name="billsafe_active" id="field_billsafe_active">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_sandbox"><?php echo $this->__('Test mode (sandbox) for BillSAFE payment') ?></label></td>
                <td class="value">
                    <select name="billsafe_sandbox" id="field_billsafe_sandbox">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_merchant_id"><?php echo $this->__('Merchant ID') ?></label></td>
                <td class="value">
                    <input type="text" name="billsafe_merchant_id" id="field_billsafe_merchant_id" class="input-text" value="<?php echo Mage::getStoreConfig('payment/billsafe/merchant_id') ?>" />
                </td>
                <td class="comment"></td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_merchant_license"><?php echo $this->__('License Key') ?></label></td>
                <td class="value">
                    <input type="text" name="billsafe_merchant_license" id="field_billsafe_merchant_license" class="input-text" value="<?php echo Mage::getStoreConfig('payment/billsafe/merchant_license') ?>" />
                </td>
                <td class="comment"><?php echo $this->__('You can find this by logging in to the <a href="%s" target="_blank">BillSAFE payment backend</a>.', 'https://client.billsafe.de/main/mainmenu') ?></td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_installment_active"><?php echo $this->__('Activate BillSAFE installment payment') ?></label></td>
                <td class="value">
                    <select name="billsafe_installment_active" id="field_billsafe_installment_active">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe_installment/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe_installment/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_installment_sandbox"><?php echo $this->__('Test mode (sandbox) for BillSAFE installment payment') ?></label></td>
                <td class="value">
                    <select name="billsafe_installment_sandbox" id="field_billsafe_installment_sandbox">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe_installment/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe_installment/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            </tbody>
        </table>
    </div>
</div>
