<?php
/**
 * Ebay edition package for Magento Localized
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalizedEbay
 * @copyright  Copyright (c) 2013 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * @see Mage_Adminhtml_Block_Template
 * @var $this Mage_Adminhtml_Block_Template
 */
?>

<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('BillSAFE') ?></h4>
    <div class="form-buttons"></div>
</div>

<div class="fieldset" id="group_billsafe">
    <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tbody>
            <tr>
                <td class="label"><label for="field_billsafe_install"><?php echo $this->__('Install BillSAFE module') ?></label></td>
                <td class="value">
                    <select name="billsafe_install" id="field_billsafe_install">
                        <option value="0"><?php echo $this->__('No') ?></option>
                        <option value="1" selected="selected"><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
                <td class="comment" rowspan="3">
                    <img src="<?php echo $this->getSkinUrl('magento_localized/logo_billsafe.png') ?>" alt="BillSAFE" />
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_active"><?php echo $this->__('Is BillSAFE payment active?') ?></label></td>
                <td class="value">
                    <select name="billsafe_active" id="field_billsafe_active">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_sandbox"><?php echo $this->__('Test mode (sandbox)') ?></label></td>
                <td class="value">
                    <select name="billsafe_sandbox" id="field_billsafe_sandbox">
                        <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/billsafe/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                        <option value="1" <?php if (Mage::getStoreConfigFlag('payment/billsafe/sandbox')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                    </select>
                </td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_merchant_id"><?php echo $this->__('Merchant ID') ?></label></td>
                <td class="value">
                    <input type="text" name="billsafe_merchant_id" id="field_billsafe_merchant_id" class="input-text" value="<?php echo Mage::getStoreConfig('payment/billsafe/merchant_id') ?>" />
                </td>
                <td class="comment"></td>
            </tr>

            <tr>
                <td class="label"><label for="field_billsafe_merchant_license"><?php echo $this->__('License Key') ?></label></td>
                <td class="value">
                    <input type="text" name="billsafe_merchant_license" id="field_billsafe_merchant_license" class="input-text" value="<?php echo Mage::getStoreConfig('payment/billsafe/merchant_license') ?>" />
                </td>
                <td class="comment"><?php echo $this->__('You can find this by logging in to the <a href="%s" target="_blank">BillSAFE payment backend</a>.', 'https://client.billsafe.de/main/mainmenu') ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</div>
