<?php
/**
 * Ebay edition package for Magento Localized
 *
 * @category   IntegerNet
 * @package    IntegerNet_MagentoLocalizedEbay
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */

/**
 * @see IntegerNet_MagentoLocalizedEbay_Block_Form
 * @var $this IntegerNet_MagentoLocalizedEbay_Block_Form
 */
?>

<?php $moduleTitle = Mage::helper('magento_localized')->__(Mage::getStoreConfig('magento_localized/module_title')) ?>

    <div class="content-header">
        <h3>
            <?php echo Mage::helper('magento_localized')->__('%s Setup', $moduleTitle) ?><br />
        </h3>
    </div>
    <h3><?php echo Mage::helper('magento_localized')->__('Page %s of %s', 3, 3) ?>: <?php echo $this->__('Setup of modules powered by PayPal') ?></h3>

<?php foreach($this->getSections() as $sectionName): ?>
    <?php foreach($this->getModules($sectionName) as $moduleName): ?>
        <?php if ($this->isModuleAvailable($moduleName)): ?>

            <div class="entry-edit-head">
                <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->getAreaHtml($moduleName, 'name') ?></h4>
            </div>

            <div class="fieldset magento-localized-ebay-setup" id="group_<?php echo $moduleName ?>">
            <div class="hor-scroll">
            <div class="col2-set">
                <div class="col-1">
                    <div class="short-description-area">
                        <?php echo $this->getAreaHtml($moduleName, 'short_description') ?>
                    </div>
                    <div class="benefits-area">
                        <?php echo $this->getAreaHtml($moduleName, 'benefits_description') ?>
                    </div>
                    <div class="general-lead-area">
                        <?php echo $this->getAreaHtml($moduleName, 'general_lead_area') ?>
                    </div>
                </div>
                <div class="col-2">
                    <div class="logo-area">
                        <?php echo $this->getAreaHtml($moduleName, 'partner_logo') ?>
                    </div>
                    <div class="image-graphic-area">
                        <?php echo $this->getAreaHtml($moduleName, 'image_graphic') ?>
                    </div>
                </div>
            </div>

            <?php if ($moduleName == 'paypal'): ?>

                <hr />

                <table cellspacing="0" class="form-list">
                    <tbody>

                    <?php if ($this->isModuleAvailable('paypalplus')): ?>
                        <tr>
                            <td class="label"><label for="field_paypalplus_active"><?php echo $this->__('Activate PayPal PLUS?') ?></label></td>
                            <td class="value">
                                <select name="paypalplus_active" id="field_paypalplus_active">
                                    <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/iways_paypalplus_payment/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    <option value="1" <?php if (Mage::getStoreConfigFlag('payment/iways_paypalplus_payment/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                                </select>
                            </td>
                        </tr>

                        <tr class="row-paypalplus">
                            <td class="label"><label for="field_paypalplus_api_client_id"><?php echo $this->__('Client ID') ?></label></td>
                            <td class="value">
                                <input type="text" name="paypalplus_api_client_id" id="field_paypalplus_api_client_id" class="input-text" value="<?php echo Mage::getStoreConfig('iways_paypalplus/api/client_id') ?>" />
                            </td>
                        </tr>

                        <tr class="row-paypalplus">
                            <td class="label"><label for="field_paypalplus_api_client_secret"><?php echo $this->__('Client Secret') ?></label></td>
                            <td class="value">
                                <input type="password" name="paypalplus_api_client_secret" id="field_paypalplus_api_client_secret" class="input-text" value="<?php echo Mage::getStoreConfig('iways_paypalplus/api/client_secret') ?>" />
                            </td>
                        </tr>

                        <tr class="row-paypalplus">
                            <td class="value">
                                <div class="ppp-buttons-container">
                                    <button id="field_paypalplus_credentionals_button" type="button" class="scalable" onclick="window.open('https://www.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=470'); return false;">
                                        <span><span><span><?php echo Mage::helper('paypal')->__('Get Credentials from PayPal') ?></span></span></span>
                                    </button>
                                </div>
                            </td>
                        </tr>

                        <tr class="row-paypalplus">
                            <td class="label"><label for="field_paypalplus_api_hdrimg"><?php echo Mage::helper('magento_localized_ebay')->__('Header Image URL') ?></label></td>
                            <td class="value">
                                <input type="text" name="paypalplus_api_hdrimg" id="field_paypalplus_api_hdrimg" class="input-text" value="<?php echo Mage::getStoreConfig('iways_paypalplus/api/hdrimg') ?>" />
                            </td>
                        </tr>

                        <tr class="row-paypalplus">
                            <td class="label"><label for="field_paypalplus_api_mode"><?php echo $this->__('Test mode (sandbox) for PayPal payment') ?></label></td>
                            <td class="value">
                                <select name="paypalplus_api_mode" id="field_paypalplus_api_mode">
                                    <option value="0" <?php if (!Mage::getStoreConfigFlag('iways_paypalplus/api/mode')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                    <option value="1" <?php if (Mage::getStoreConfigFlag('iways_paypalplus/api/mode')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                                </select>
                            </td>
                        </tr>

                    <?php endif ?>

                    <tr class="row-paypal">
                        <td class="label" rowspan="2"><label for="field_paypal_express_email"><?php echo $this->__('Email Associated with PayPal Merchant Account') ?></label></td>
                        <td class="value">
                            <input type="text" name="paypal_express_email" id="field_paypal_express_email" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/general/business_account') ?>" />
                        </td>
                        <td class="comment" rowspan="9">
                            <?php echo $this->getAreaHtml($moduleName, 'module_settings_description') ?>
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="value">
                            <div class="pp-buttons-container">
                                <button id="payment_express_checkout_required_express_checkout_api_wizard" type="button" class="scalable" onclick="window.open('https://www.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=470'); return false;">
                                    <span><span><span><?php echo Mage::helper('paypal')->__('Get Credentials from PayPal') ?></span></span></span>
                                </button>
                            </div>
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label"><label for="field_paypal_api_username"><?php echo Mage::helper('paypal')->__('API Username') ?></label></td>
                        <td class="value">
                            <input type="password" name="paypal_api_username" id="field_paypal_api_username" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/wpp/api_username') ?>" />
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label"><label for="field_paypal_api_password"><?php echo Mage::helper('paypal')->__('API Password') ?></label></td>
                        <td class="value">
                            <input type="password" name="paypal_api_password" id="field_paypal_api_password" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/wpp/api_password') ?>" />
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label" rowspan="2"><label for="field_paypal_api_signature"><?php echo Mage::helper('paypal')->__('API Signature') ?></label></td>
                        <td class="value">
                            <input type="password" name="paypal_api_signature" id="field_paypal_api_signature" class="input-text" value="<?php echo Mage::getStoreConfig('paypal/wpp/api_signature') ?>" />
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label">
                            <div class="pp-buttons-container">
                                <button id="sandbox_payment_express_checkout_required_express_checkout_api_wizard" type="button" class="scalable" onclick="javascript:window.open('https://www.sandbox.paypal.com/us/cgi-bin/webscr?cmd=_login-api-run', 'apiwizard','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=100, top=100, width=380, height=470'); return false;">
                                    <span><span><span><?php echo Mage::helper('paypal')->__('Sandbox Credentials') ?></span></span></span>
                                </button>
                            </div>
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label"><label for="field_paypal_active"><?php echo $this->__('Activate PayPal Express payment') ?></label></td>
                        <td class="value">
                            <select name="paypal_active" id="field_paypal_active">
                                <option value="0" <?php if (!Mage::getStoreConfigFlag('payment/paypal_express/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                <option value="1" <?php if (Mage::getStoreConfigFlag('payment/paypal_express/active')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr class="row-paypal">
                        <td class="label"><label for="field_paypal_sandbox"><?php echo $this->__('Test mode (sandbox) for PayPal payment') ?></label></td>
                        <td class="value">
                            <select name="paypal_sandbox" id="field_paypal_sandbox">
                                <option value="0" <?php if (!Mage::getStoreConfigFlag('paypal/wpp/sandbox_flag')): ?>selected="selected"<?php endif ?>><?php echo $this->__('No') ?></option>
                                <option value="1" <?php if (Mage::getStoreConfigFlag('paypal/wpp/sandbox_flag')): ?>selected="selected"<?php endif ?>><?php echo $this->__('Yes') ?></option>
                            </select>
                        </td>
                    </tr>

                    <tr>
                        <td class="label" colspan="2">
                            <?php echo $this->__('You have the option to make further settings for PayPal after you finished the setup here.') ?>
                        </td>
                    </tr>

                    </tbody>
                </table>

                <script type="text/javascript">
                    var paypalplusActiveField = $('field_paypalplus_active');
                    var updatePayPalFieldsVisibility = function () {
                        if (paypalplusActiveField.value == '1') {
                            $$('.row-paypalplus').each(function (element) {
                                element.show();
                            });
                            $$('.row-paypal').each(function (element) {
                                element.hide();
                            });
                        } else {
                            $$('.row-paypalplus').each(function (element) {
                                element.hide();
                            });
                            $$('.row-paypal').each(function (element) {
                                element.show();
                            });
                        }
                    };
                    if (paypalplusActiveField) {
                        updatePayPalFieldsVisibility();
                        paypalplusActiveField.observe('change', function() {
                            updatePayPalFieldsVisibility();
                        });
                    }
                </script>

            <?php endif ?>
            </div>
            </div>
        <?php endif ?>
    <?php endforeach ?>
<?php endforeach ?>