<!DOCTYPE html>
<html lang="de" class="no-js">
<head>
    <title>Erfahren Sie mehr über die Vorteile von PayPal</title>
    <meta charset="utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content="Finden Sie heraus warum PayPal einfach, sicher und flexibel ist."/>
    <link rel="canonical" href="https://www.paypal.com/de/webapps/mpp/paypal-popup"/>
    <link rel="shortcut icon" href="https://www.paypalobjects.com/en_US/i/icon/pp_favicon_x.ico"/>
    <link rel="apple-touch-icon" href="https://www.paypalobjects.com/en_US/i/pui/apple-touch-icon.png"/>
    <link href="https://www.paypalobjects.com/eboxapps/css/1b/b03f83ac7540a0454b799dcac6c9dc.css" rel="stylesheet"
          type="text/css"/>
    <!--[if lt IE 10 & gte IE 8]>
    <link href="https://www.paypalobjects.com/eboxapps/css/2d/30552c894b3d71a6024d35c7c723c2.css" rel="stylesheet"
          type="text/css"/><![endif]-->
    <!--[if IE 8]>
    <link href="https://www.paypalobjects.com/eboxapps/css/c7/2a490b51c43543978952f663bff976.css" rel="stylesheet"
          type="text/css"/><![endif]-->
    <!--[if IE 7]>
    <link href="https://www.paypalobjects.com/eboxapps/css/2b/4b19e3c492e634f16742b775d7957f.css" rel="stylesheet"
          type="text/css"/><![endif]-->
    <!--[if IE 6]>
    <link href="https://www.paypalobjects.com/eboxapps/css/d2/435f313aee42f7cd87eec90cfbb45d.css" rel="stylesheet"
          type="text/css"/><![endif]-->
    <style id="antiClickjack">
        body {
            display: none !important;
        }
    </style>
    <style type="text/css">
        #de-popup-container {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 715px;
            padding: 16px;
        }

        body, #page, #content, #main, .contentWrapper {
            min-width: 715px !important;
        }

        .contentWrapper {
            width: 715px !important
        }</style>
    <script>
        if (self === top) {
            var antiClickjack = document.getElementById("antiClickjack");
            antiClickjack.parentNode.removeChild(antiClickjack);
        } else {
            top.location = self.location;
        }
    </script>
    <script src="https://www.paypalobjects.com/eboxapps/js/4f/69701698e85a59c86ad8082c50ca54.js"
            type="text/javascript"></script>
</head>
<body class="loggedOut">
<noscript>
    <p class="nonjsAlert" role="alert">
    </p>
</noscript>
<div id="page">
    <section id="content">
        <section id="main">
            <div class="contentWrapper">
                <div id="de-popup-container" class="wtDiv editBorder ">
                    <div id="columns_wttwocolumnsadvanced_0" class="catWidget columnContainer nsb_16_8">
                        <div class="one column">
                            <div style="line-height:7px"></div>
                            <div class="catWidget imageContainer imageAlignLeft"><img
                                    src="https://www.paypalobjects.com/webstatic/i/ex_ce2/logo/logo_paypal_106x28.png">
                            </div>
                        </div>
                        <div class="two column nogutter">
                            <div class="catWidget buttonContainer leftAlign fullwidth"><a
                                    class="catWidget button medium leftAlign default "
                                    href="https://www.paypal.com/de/webapps/mpp/referral/paypal-business-account2?partner_id=magentodeedition">Kostenlos
                                    anmelden</a></div>
                        </div>
                    </div>
                    <h3>Sicher und einfach bezahlen – so geht’s</h3>

                    <div class="catWidget iconTextContainer positionLeft" style="min-height: 48px;">
                        <div class="iconWrapper"><img
                                src="https://www.paypalobjects.com/webstatic/de_DE/i/icon-anmelden.png"></div>
                        <div class="textWrapper" style="padding: 0 0 0 68px;">
                            <ol>
                                <li><strong>Einfach anmelden</strong><br/> Melden Sie sich kostenlos bei PayPal an und
                                    hinterlegen Sie einmalig Ihre Bankdaten. Bei jedem zukünftigen Einkauf mit PayPal
                                    benötigen Sie nur noch Ihre E-Mail-Adresse und Ihr Passwort. Somit brauchen Sie Ihre
                                    Finanzdaten bei den nächsten Einkäufen nicht mehr anzugeben.
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div class="catWidget iconTextContainer positionLeft" style="min-height: 48px;">
                        <div class="iconWrapper"><img
                                src="https://www.paypalobjects.com/webstatic/de_DE/i/icon-sicher.png"></div>
                        <div class="textWrapper" style="padding: 0 0 0 68px;">
                            <ol start="2">
                                <li><strong>Auf Nummer sicher gehen</strong><br/> Ihre Daten sind bei uns wie in einem
                                    Schließfach sicher hinterlegt. Darüber hinaus haben wir den kostenlosen
                                    PayPal-Käuferschutz eingerichtet: Sollte mal was schief gehen, erhalten Sie Ihr Geld
                                    zurück.<br/> <br/></li>
                            </ol>
                        </div>
                    </div>
                    <div class="catWidget iconTextContainer positionLeft" style="min-height: 48px;">
                        <div class="iconWrapper"><img
                                src="https://www.paypalobjects.com/webstatic/de_DE/i/icon-flexibel-einkaufne.png"></div>
                        <div class="textWrapper" style="padding: 0 0 0 68px;">
                            <ol start="3">
                                <li><strong>Flexibel bleiben</strong><br/> Von A wie Alternate bis Z wie Zalando, mit
                                    PayPal können Sie in zahlreichen Online-Shops bezahlen – online und mobil. Und falls
                                    Sie Ihre Kreditkarte mit Bonusprogramm in Ihrem PayPal-Konto hinterlegen, sammeln
                                    Sie selbstverständlich weiterhin Ihre Punkte.
                                </li>
                            </ol>
                        </div>
                    </div>
                    <div id="columns_wtfourcolumns_0" class="catWidget columnContainer nsb_5_7_5_7">
                        <div class="one column"><p><strong>Für Privatkunden</strong></p>

                            <p><a href="https://www.paypal.com/de/webapps/mpp/kaufen">PayPal-Vorteile</a><br/><a
                                    href="https://www.paypal.com/de/webapps/mpp/kaufen-wie">Zahlen mit PayPal</a><br/><a
                                    href="https://www.paypal.com/einkaufswelt">PayPal-Angebote</a><br/><a
                                    class="pageTrigger" href="https://www.paypal.com/de/webapps/mpp/buyer-protection">PayPal-Käuferschutz</a>
                            </p></div>
                        <div class="two column"><p><strong>Für Geschäftskunden</strong></p>

                            <p><a class="pageTrigger" href="https://www.paypal.com/de/webapps/mpp/home-merchant">Zum
                                    Geschäftskundenportal</a><br/><a
                                    href="https://www.paypal.com/de/webapps/mpp/solutions">PayPal-Lösungen</a><br/><a
                                    href="https://www.paypal.com/de/webapps/mpp/sell-mobile">Mobil verkaufen</a><br/><a
                                    href="https://www.paypal.com/de/webapps/mpp/billsafe">BillSAFE integrieren</a></p>
                        </div>
                        <div class="three column"><p><strong>Social Media</strong></p>

                            <p><a href="https://www.paypal.com/blog">PayPal-Blog</a><br/><a class="pageTrigger"
                                                                                            href="https://www.facebook.com/PayPalDeutschland">PayPal
                                    auf Facebook</a><br/><a href="https://www.twitter.com/PayPalDE">PayPal auf
                                    Twitter</a><br/><a href="http://www.youtube.com/user/paypalde">PayPal auf
                                    YouTube</a></p></div>
                        <div class="column nogutter"><p><strong>PayPal mobil</strong></p>

                            <p><a class="pageTrigger"
                                  href="https://www.paypal.com/de/cgi-bin/webscr?cmd=register-security-key-mobile">PayPal-Sicherheitsschlüssel</a><br/><a
                                    href="https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile&amp;hl=de">PayPal-Android-App</a><br/><a
                                    href="http://itunes.apple.com/de/app/paypal/id283646709?mt=8">PayPal-iPhone-App</a><br/><a
                                    href="https://www.paypal-deutschland.de/privatkunden/qrshopping.html">PayPal
                                    QRShopping</a></p></div>
                    </div>
                </div>
            </div>
        </section>
    </section>
</div>

</body>
</html>
